# Change these first
owner: wk722 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com/
  - name: BazQux Reader
    url: https://bazqux.com/
  - name: Hacker News
    url: https://news.ycombinator.com/
  - name: SourceHut Git
    url: https://git.sr.ht/
  - name: linkhut
    url: https://ln.ht/
  - name: Castlery SG
    url: https://www.castlery.com/sg
  - name: Castlery AU
    url: https://www.castlery.com/au
  - name: Castlery US
    url: https://www.castlery.com/us
  - name: Castlery CA
    url: https://www.castlery.com/ca
  - name: Castlery UK
    url: https://www.castlery.com/uk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: wk722 status
  # introTitle: "**Demosite**"
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  # navbar:
  #   - title: Status
  #     href: /
  #   - title: GitHub
  #     href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
